spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mp_study?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/mp_study?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
logging:
  level:
    root: warn
    com.xz.mpstudy.mapper: trace
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: id_worker
#      insert-strategy: not_empty
#      table-prefix: mp_
#  config-location: classpath*:mybatis-config.xml
#  type-aliases-package: com.xz.mpstudy.entity
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
